"use client";
import {useState} from "react";

const features=[
 {id:"wo",tab:"Ажлын захиалга",kicker:"WORK ORDER MANAGEMENT",title:"Ажлыг хүсэлтээс хаалт хүртэл нэг урсгалаар",text:"Request → WO Request → Planning → Approval → OPEN WO дараалалтай. Төлөвлөгч ажиллах хүч, хугацаа, сэлбэг, төсөв болон HSE шаардлагыг тодорхойлж, эрх бүхий ажилтан батална.",points:["Ажилтан, хугацаа, Timeline төлөвлөлт","Материал, зардал, чеклистийн бүртгэл","Гүйцэтгэл, хаалт, хөрөнгийн түүх"],screen:"work"},
 {id:"pm",tab:"Урьдчилан сэргийлэх засвар",kicker:"PREVENTIVE MAINTENANCE",title:"PM Engine ажлыг хөрөнгө бүрээр автоматаар үүсгэнэ",text:"Хуваарь болон сонгосон хөрөнгийн нөхцөлөөр PM үүснэ. PM батлагдаж Эхлэх команд өгсний дараа Engine ажиллаж, хөрөнгө тус бүрд дахин баталгаажуулалтгүй Батлагдсан WO бий болгоно.",points:["Хуваарийн төрөл: Direct, Completed","Олон хөрөнгөд тус тусын WO","PM-ээс үүссэн WO шууд батлагдана"],screen:"pm"},
 {id:"asset",tab:"Хөрөнгийн удирдлага",kicker:"ASSET-CENTERED EAM",title:"Бүх өгөгдөл хөрөнгийн нэг түүх дээр",text:"Байршил, шаталсан бүтэц, техникийн үзүүлэлт, баримт бичиг, BOM, засварын түүх, зогсолт, зардал, гэрээ болон эрсдэлийг нэг хөрөнгийн профайлаас харна.",points:["Хөрөнгийн шаталсан бүтэц","Parts Master ба BOM холбоос","Амьдралын мөчлөгийн зардал, түүх"],screen:"asset"},
 {id:"insight",tab:"Тайлан ба AI",kicker:"INSIGHTS & INTELLIGENCE",title:"Бодит өгөгдлөөс дараагийн зөв шийдвэрт",text:"Динамик тайлан, KPI, эвдрэлийн шинжилгээ болон PdM trigger-ийг нэгтгэнэ. AI эхний шатанд зөвхөн уншиж, тайлбарлаж, зөвлөмж өгнө; үйлдлийн эрхийг Directus шийднэ.",points:["MTBF, MTTR, PM compliance, downtime","Generated PdM → Accept → WO","Open-source эхлэл, provider сольж болох AI"],screen:"report"}
];
const modules=["Хөрөнгө","Хүсэлт","Ажлын захиалга","Timeline / Ажиллах хүч","PM","PdM","Үзлэг шалгалт","Агуулах / Нөөц","Parts Master / BOM","Төсөв / Зардал","Гүйцэтгэгч / Төсөл / Гэрээ","My Task / Mobile","Тайлан / KPI","HSE / Shared"];

export default function Home(){const [active,setActive]=useState(0);const f=features[active];return <main>
 <div className="topbar">Монгол инженерүүдийн бүтээсэн хөрөнгийн удирдлагын нэгдсэн систем <a href="#ai">AI хөгжүүлэлт →</a></div>
 <nav className="nav shell"><a className="brand" href="#top"><b>i</b>BeX <small>eAM</small></a><div className="links"><a href="#platform">Платформ</a><a href="#flow">Процесс</a><a href="#modules">Модулиуд</a><a href="#architecture">Архитектур</a></div><div className="navright"><a className="login" href="https://demo.ibex.mn">Нэвтрэх</a><a className="btn mini" href="mailto:info@ibex.mn?subject=iBeX demo">Демо хүсэх</a></div></nav>

 <section className="hero" id="top"><div className="shell heroGrid"><div className="heroCopy"><div className="rating"><span>★★★★★</span> Хөрөнгө төвтэй EAM / CMMS</div><h1>Хөрөнгө найдвартай.<br/>Үйл ажиллагаа <em>тасралтгүй.</em></h1><p>Засварын хүсэлт, ажлын захиалга, PM, сэлбэг, төсөв, гэрээ болон тайланг нэг өгөгдлийн урсгалд удирдана.</p><div className="actions"><a className="btn" href="mailto:info@ibex.mn?subject=iBeX demo">Демо товлох <b>→</b></a><a className="outline" href="#platform">Системийг үзэх</a></div><small>Олон компани · Олон хэл · Cloud эсвэл Standalone</small></div><HeroVisual/></div><div className="wave"/></section>

 <section className="proof"><div className="shell"><p>НЭГ СИСТЕМЭЭР УДИРДАХ ҮНДСЭН ХҮРЭЭ</p><div className="proofrow"><span>ASSET</span><span>WORK</span><span>PM / PdM</span><span>INVENTORY</span><span>BUDGET</span><span>HSE</span></div></div></section>

 <section className="platform shell" id="platform"><div className="center"><label>iBeX ПЛАТФОРМ</label><h2>Илүү ухаалаг засвар.<br/>Илүү тогтвортой үйлдвэрлэл.</h2><p>Техник ашиглагч, төлөвлөгч, инженер, батлагч болон удирдлагыг нэг мэдээллийн орчинд холбоно.</p></div><div className="tabs">{features.map((x,i)=><button className={active===i?"active":""} onClick={()=>setActive(i)} key={x.id}>{x.tab}</button>)}</div><div className="feature"><div className="featureCopy"><label>{f.kicker}</label><h3>{f.title}</h3><p>{f.text}</p><ul>{f.points.map(p=><li key={p}>✓ <span>{p}</span></li>)}</ul><a href="#flow">Процесс харах →</a></div><ProductScreen type={f.screen}/></div></section>

 <section className="dark" id="flow"><div className="shell"><div className="twocol"><div><label>БАТАЛГААЖСАН ПРОЦЕСС</label><h2>Хүсэлт бүр<br/>хэмжигдэх ажил болно.</h2></div><p>Хэрэглэгчийн гарын авлагын дэлгэцийн нэршил, Flowchart-ийн approval болон decision дүрмийг нэгтгэсэн үндсэн урсгал.</p></div><div className="process"><article><b>01</b><i>!</i><h3>Request</h3><p>Created Requests → Open Jobs → Completed Requests</p></article><span>→</span><article><b>02</b><i>⌁</i><h3>WO Request</h3><p>Ажлын цар хүрээ, төрөл, эрэмбэ тогтооно</p></article><span>→</span><article><b>03</b><i>▤</i><h3>Planning</h3><p>Timeline, ажиллах хүч, материал, HSE</p></article><span>→</span><article><b>04</b><i>✓</i><h3>Approval</h3><p>Эрх бүхий ажилтан шийдвэрлэнэ</p></article><span>→</span><article><b>05</b><i>▶</i><h3>OPEN WO</h3><p>Гүйцэтгэл → хаалт → Asset History</p></article></div><div className="rule"><b>PM тусгай дүрэм</b><span>PM → Asset → Approve → Start → PM Engine → хөрөнгө бүрт Батлагдсан WO</span><em>Дахин батлуулахгүй</em></div></div></section>

 <section className="moduleSection shell" id="modules"><div className="center"><label>БҮРЭН ХАМРАХ ХҮРЭЭ</label><h2>Хөрөнгийн амьдралын мөчлөгт<br/>хэрэгтэй бүх модуль.</h2></div><div className="moduleGrid">{modules.map((m,i)=><article key={m}><span>{String(i+1).padStart(2,"0")}</span><b>{["◇","!","✓","◷","↻","⌁","☷","▦","⊞","₮","▤","◉","▥","+"][i]}</b><h3>{m}</h3><a href="mailto:info@ibex.mn?subject=iBeX module">→</a></article>)}</div></section>

 <section className="outcomes"><div className="shell"><div><label>НЭГДСЭН ХАРАГДАЦ</label><h2>Үйлдвэрлэлийн “сохор цэг”-ийг арилгана.</h2></div><div className="outcomeGrid"><article><b>01</b><h3>Үйлдвэрлэл ба засварыг холбоно</h3><p>Хүсэлт, ажлын хуваарь, зогсолт, HSE мэдээллийг нэг Timeline-д уялдуулна.</p></article><article><b>02</b><h3>Зардал ба ROI-г нотолно</h3><p>Хөрөнгө, WO, материал, ажиллах хүч, төсөв, гэрээний зардлыг хянаж шийдвэр гаргана.</p></article><article><b>03</b><h3>Аюулгүй, аудитад бэлэн</h3><p>Үзлэг, чеклист, зөвшөөрөл, гүйцэтгэлийн нотолгоог хөрөнгийн түүхэд хадгална.</p></article></div></div></section>

 <section className="ai shell" id="ai"><div className="aiCopy"><label>ИРЭЭДҮЙН ХӨГЖҮҮЛЭЛТ</label><h2>Урьдчилан таамаглах засвар ба Generative AI</h2><p>Эхний production шатанд AI нь Asset, WO, PM мэдээлэл хайх, SOP/RAG, түүх хураангуйлах, тайлбар болон зөвлөмж өгөх read-only туслах байна. Үндсэн iBeX нь AI-гүй үед ч хэвийн ажиллана.</p><div className="aiSteps"><span><b>1</b>Read-only AI</span><span><b>2</b>PdM trigger</span><span><b>3</b>Human approval</span></div></div><div className="aiMap"><div>Vue / Nuxt<small>Хэрэглэгчийн интерфэйс</small></div><i>→</i><div>Directus<small>Auth · Role · Tenant</small></div><i>→</i><div>AI Service<small>Open-source first</small></div><i>→</i><div>PostgreSQL<small>Үнэн зөв өгөгдөл</small></div></div></section>

 <section className="architecture" id="architecture"><div className="shell archGrid"><div><label>УЯН ХАТАН БАЙРШУУЛАЛТ</label><h2>Танай байгууллагын бүтцэд тохирно.</h2></div><div className="archCards"><article><b>Multi-tenant</b><p>Олон компанийг нэг системд, tenant/company/role түвшинд тусгаарлан удирдана.</p></article><article><b>Standalone</b><p>Байгууллагад зориулсан тусдаа сервер, өгөгдлийн сан бүхий хувилбар.</p></article><article><b>Олон хэл</b><p>Монгол болон бусад хэлээр байгууллага, хэрэглэгчийн түвшинд ажиллана.</p></article></div></div></section>

 <section className="cta"><div className="shell"><div><label>eAM iBeX-ТЭЙ ТАНИЛЦАХ УУ?</label><h2>Хөрөнгийн бүтээмжээ<br/>өнөөдрөөс сайжруул.</h2></div><a className="btn light" href="mailto:info@ibex.mn?subject=iBeX demo">Демо товлох →</a></div></section>
 <footer><div className="shell footTop"><div><a className="brand invert" href="#top"><b>i</b>BeX <small>eAM</small></a><p>Хөрөнгийг төв болгосон засвар үйлчилгээ, нөөц ба зардлын нэгдсэн удирдлага.</p></div><div><b>Платформ</b><a href="#platform">Ажлын захиалга</a><a href="#platform">PM / PdM</a><a href="#modules">Хөрөнгө ба нөөц</a><a href="#ai">AI хөгжүүлэлт</a></div><div><b>Шийдэл</b><a href="#flow">Процесс</a><a href="#architecture">Multi-tenant</a><a href="#architecture">Standalone</a><a href="#platform">Mobile</a></div><div><b>Холбоо</b><a href="https://demo.ibex.mn">demo.ibex.mn</a><a href="mailto:info@ibex.mn">info@ibex.mn</a></div></div><div className="shell copyright">© 2026 eAM iBeX <span>Монгол инженерүүдийн бүтээл</span></div></footer>
 </main>}

function HeroVisual(){return <div className="heroVisual"><div className="photo"><div className="worker"><i/><b>iBeX</b><span>ENGINEER</span></div></div><div className="laptop"><div className="laptopbar"><b><i>i</i>BeX</b><span>⌕ &nbsp; ●</span></div><div className="laptopbody"><aside>{["▦","◇","✓","↻","▥"].map(x=><i key={x}>{x}</i>)}</aside><section><small>ХЯНАЛТЫН САМБАР</small><h4>Засварын гүйцэтгэл</h4><div className="metrics"><p><span>OPEN WO</span><b>36</b></p><p><span>PM COMPLIANCE</span><b>94.8%</b></p><p><span>ASSET HEALTH</span><b>92%</b></p></div><div className="bars">{[42,63,50,80,68,91,76].map((h,i)=><i key={i} style={{height:h+"%"}}/>)}</div></section></div></div><div className="float"><b>✓</b><p><small>PM ENGINE</small><strong>WO автоматаар үүслээ</strong></p></div></div>}

function ProductScreen({type}:{type:string}){return <div className="productScreen"><div className="screenNav"><b><i>i</i>BeX</b><span>Хяналтын самбар</span><span>Хөрөнгө</span><span className="sel">Ажлын удирдлага</span><span>Агуулах</span><span>Тайлан</span></div><div className="screenMain"><header><div><small>{type.toUpperCase()} / IBEX</small><h4>{type==="pm"?"Урьдчилан сэргийлэх засвар":type==="asset"?"Хөрөнгийн бүртгэл":type==="report"?"Гүйцэтгэлийн шинжилгээ":"Ажлын захиалгууд"}</h4></div><button>+ Шинэ</button></header>{type==="report"?<ReportUI/>:type==="asset"?<AssetUI/>:<TableUI pm={type==="pm"}/>}</div></div>}
function TableUI({pm}:{pm:boolean}){return <><div className="filters"><span>⌕ Хайх...</span><span>Төлөв ▾</span><span>Огноо ▾</span></div><div className="table"><b><span>ID</span><span>{pm?"PM НЭР":"АЖЛЫН НЭР"}</span><span>ХӨРӨНГӨ</span><span>ХАРИУЦАГЧ</span><span>ТӨЛӨВ</span></b>{[["#1048",pm?"7 хоногийн үзлэг":"Насосны холхивч солих","P-104","Б. Тэмүүлэн","OPEN"],["#1047",pm?"250 цагийн үйлчилгээ":"Конвейерийн тууз шалгах","CV-02","Г. Бат","PLANNING"],["#1046",pm?"Сарын тосолгоо":"Моторын чичиргээ хэмжих","M-208","Д. Сүх","APPROVED"],["#1045",pm?"Жилийн их үзлэг":"Компрессорын шүүлтүүр","C-301","А. Энх","COMPLETED"]].map(r=><p key={r[0]}>{r.map((c,i)=><span className={i===4?"status":""} key={c}>{c}</span>)}</p>)}</div></>}
function AssetUI(){return <div className="assetUI"><aside><div className="assetpic">◇</div><h5>Насос P-104</h5><small>Технологийн усны систем</small><b>● АЖИЛЛАЖ БАЙНА</b><hr/><p>Байршил <strong>Баяжуулах үйлдвэр / 2-р шугам</strong></p><p>Чухал түвшин <strong>Өндөр</strong></p></aside><section><div className="assetStats"><p><small>БЭЛЭН БАЙДАЛ</small><b>96.4%</b></p><p><small>НИЙТ ЗАРДАЛ</small><b>₮12.8M</b></p><p><small>OPEN WO</small><b>2</b></p></div><h5>Засварын түүх</h5>{["Холхивч солив","Тосолгоо хийв","Чичиргээний үзлэг"].map((x,i)=><div className="history" key={x}><i>✓</i><span><b>{x}</b><small>WO-10{44-i} · 2026.08.{14-i}</small></span></div>)}</section></div>}
function ReportUI(){return <div className="reportUI"><div className="reportCards"><p><small>MTBF</small><b>426 цаг</b><em>↑ 8.4%</em></p><p><small>MTTR</small><b>3.2 цаг</b><em>↓ 12%</em></p><p><small>PM COMPLIANCE</small><b>94.8%</b><em>↑ 2.4%</em></p></div><div className="linechart"><h5>Төлөвлөгөөт ба төлөвлөгөөт бус ажил</h5><svg viewBox="0 0 500 140"><polyline points="0,110 70,85 140,94 210,48 280,67 350,30 420,40 500,15"/><polyline className="orange" points="0,70 70,92 140,66 210,90 280,80 350,105 420,89 500,101"/></svg></div></div>}
