const modules=[["◇","Хөрөнгийн удирдлага","Байршил, бүтэц, түүх, техникийн өгөгдлийг нэг цэгээс удирдана."],["✓","Ажлын захиалга","Хүсэлтээс гүйцэтгэл хүртэлх ажлыг бодит хугацаанд хянана."],["↻","Урьдчилан сэргийлэх засвар","Хуваарь болон хөрөнгийн нөхцөлөөр ажлыг автоматаар үүсгэнэ."],["▦","Агуулах ба сэлбэг","Нөөц, зарцуулалт, захиалга, өртгийн хөдөлгөөнийг хянана."],["₮","Төсөв, төсөл, гэрээ","Зардал, төсвийн хамралт, төслийн гүйцэтгэлийг нэгтгэнэ."],["⌁","Тайлан ба шинжилгээ","Шийдвэр гаргалтад зориулсан динамик үзүүлэлт гаргана."]];
export default function Home(){return <main>
 <nav className="nav shell"><a className="brand" href="#top"><b>i</b>BeX</a><div className="links"><a href="#solution">Шийдэл</a><a href="#modules">Модулиуд</a><a href="#future">Хөгжүүлэлт</a></div><a className="btn small" href="mailto:info@ibex.mn?subject=iBeX demo">Демо хүсэх ↗</a></nav>
 <section className="hero shell" id="top"><div><label>— МОНГОЛ ИНЖЕНЕРҮҮДИЙН БҮТЭЭСЭН EAM</label><h1>Хөрөнгийн бүтээмжийг<br/><em>шинэ түвшинд.</em></h1><p>eAM iBeX нь тоног төхөөрөмж, засвар үйлчилгээ, нөөц болон зардлыг нэгтгэн удирдах ухаалаг платформ.</p><div className="actions"><a className="btn" href="mailto:info@ibex.mn?subject=iBeX demo">Үнэгүй демо авах →</a><a href="#solution">▶ &nbsp; Системтэй танилцах</a></div></div><Dashboard/></section>
 <section className="stats"><div className="shell"><p><b>99.9%</b>Системийн хүртээмж</p><p><b>24/7</b>Хөрөнгийн хяналт</p><p><b>1</b>Нэгдсэн мэдээллийн сан</p></div></section>
 <section className="section shell" id="solution"><header><div><label>— НЭГДСЭН ШИЙДЭЛ</label><h2>Засварын ажлыг<br/>илүү <em>ойлгомжтой.</em></h2></div><p>Цаасан бүртгэл, салангид хүснэгтээс татгалзаж, хөрөнгийн бүх мөчлөгийг нэг мэдээллийн урсгалд оруулна.</p></header><div className="flow">{[["01","Хүсэлт","Асуудлыг веб эсвэл гар утсаас бүртгэнэ"],["02","Төлөвлөлт","Нөөц, ажилтан, хугацааг хуваарилна"],["03","Гүйцэтгэл","Ажлын явцыг бодит хугацаанд хянана"],["04","Шинжилгээ","Үр дүнг хэмжиж, шийдвэр гаргана"]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
 <section className="modules" id="modules"><div className="shell"><label>— ҮНДСЭН БОЛОМЖУУД</label><h2>Нэг платформ.<br/><em>Бүх үйл ажиллагаа.</em></h2><div className="grid">{modules.map((m,i)=><article key={m[1]}><small>0{i+1}</small><i>{m[0]}</i><h3>{m[1]}</h3><p>{m[2]}</p><a href="mailto:info@ibex.mn">Дэлгэрэнгүй →</a></article>)}</div></div></section>
 <section className="future shell" id="future"><div><label>— ИРЭЭДҮЙН ХӨГЖҮҮЛЭЛТ</label><h2>Өгөгдлөөс<br/><em>урьдчилан таамаглалд.</em></h2><p>Монгол инженерүүдийн аргачлал, хиймэл оюуны технологид суурилсан урьдчилан таамаглах засвар болон Generative AI туслах.</p><a className="btn white" href="mailto:info@ibex.mn?subject=iBeX cooperation">Хамтран ажиллах →</a></div><div className="orb"><b>AI</b></div></section>
 <footer><div className="shell"><a className="brand" href="#top"><b>i</b>BeX</a><p>Хөрөнгийн удирдлагын ухаалаг шийдэл.</p><a href="mailto:info@ibex.mn">info@ibex.mn</a><small>© 2026 eAM iBeX</small></div></footer>
 </main>}
function Dashboard(){return <div className="visual"><div className="dash"><aside><b>i</b><span>▦</span><span>◇</span><span>✓</span><span>⌁</span></aside><section><header><div><small>ХЯНАЛТЫН САМБАР</small><strong>Өдрийн мэнд, Инженер</strong></div><b>GE</b></header><div className="cards"><p><small>НИЙТ ХӨРӨНГӨ</small><b>1,248</b><em>↑ 12%</em></p><p><small>НЭЭЛТТЭЙ АЖИЛ</small><b>36</b><em>8 яаралтай</em></p><p><small>БЭЛЭН БАЙДАЛ</small><b>94.8%</b><em>↑ 2.4%</em></p></div><div className="chart"><strong>Засварын гүйцэтгэл</strong><div>{[30,45,38,63,56,78,90].map((h,i)=><i key={i} style={{height:h+"%"}}/>)}</div></div><div className="done"><b>94%</b><p><strong>Төлөвлөгөөт ажил</strong><small>Хугацаандаа гүйцэтгэсэн</small></p></div></section></div><div className="notice">✓ <p><small>АЖЛЫН ЗАХИАЛГА</small><b>Автоматаар үүслээ</b></p></div></div>}
