import {env} from 'cloudflare:workers';
import {NextResponse} from 'next/server';
import {getAdminSession,hasAdminPermission} from '../../../lib/site-admin';

const KEY='socialContent';
const reply=(body:unknown,status=200)=>NextResponse.json(body,{status,headers:{'Cache-Control':'no-store'}});
async function authorized(){const user=await getAdminSession();return{user,error:!user?reply({error:'Админ нэвтрэлт шаардлагатай.'},401):!hasAdminPermission(user,'social.manage')?reply({error:'Мэдээ, контент удирдах эрхгүй.'},403):null};}
function facebookUrl(value:unknown){try{const url=new URL(String(value));if(url.protocol!=='https:')return null;const host=url.hostname.toLowerCase();if(!['facebook.com','www.facebook.com','m.facebook.com','fb.watch'].includes(host))return null;url.hash='';return url.toString();}catch{return null;}}
function meta(html:string,property:string){const safe=property.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const patterns=[new RegExp(`<meta[^>]+(?:property|name)=["']${safe}["'][^>]+content=["']([^"']*)["']`,'i'),new RegExp(`<meta[^>]+content=["']([^"']*)["'][^>]+(?:property|name)=["']${safe}["']`,'i')];for(const pattern of patterns){const value=html.match(pattern)?.[1];if(value)return value.replace(/&amp;/g,'&').replace(/&quot;/g,'"').slice(0,5000);}return'';}
function normalize(rows:unknown){if(!Array.isArray(rows))return[];return rows.slice(0,200).map((r:any)=>({id:String(r?.id||crypto.randomUUID()).slice(0,100),sourceUrl:facebookUrl(r?.sourceUrl)||'',type:['post','reel','event','update','research'].includes(r?.type)?r.type:'post',title:String(r?.title||'').slice(0,300),text:String(r?.text||'').slice(0,12000),imageUrl:String(r?.imageUrl||'').slice(0,2000),publishedAt:String(r?.publishedAt||'').slice(0,100),status:['draft','published','archived'].includes(r?.status)?r.status:'draft',enabled:r?.enabled!==false})).filter(r=>r.sourceUrl);}
async function read(){const row=await env.DB.prepare('SELECT value_json FROM site_content WHERE key=?').bind(KEY).first<{value_json:string}>();try{return normalize(row?JSON.parse(row.value_json):[]);}catch{return[];}}
export async function GET(){const {error}=await authorized();if(error)return error;return reply({entries:await read()});}
export async function POST(request:Request){const {error}=await authorized();if(error)return error;const body=await request.json().catch(()=>({})),sourceUrl=facebookUrl(body.url);if(!sourceUrl)return reply({error:'Facebook post эсвэл Reel-ийн зөв HTTPS холбоос оруулна уу.'},400);const existing=await read();if(existing.some(row=>row.sourceUrl===sourceUrl))return reply({error:'Энэ холбоос өмнө бүртгэгдсэн байна.'},409);let title='',text='',imageUrl='',importStatus='needs_manual_review';try{const response=await fetch(sourceUrl,{headers:{'user-agent':'Mozilla/5.0 iBeX-Site-Content-Importer/1.0'},signal:AbortSignal.timeout(6000),redirect:'follow'});if(response.ok){const html=(await response.text()).slice(0,1000000);title=meta(html,'og:title');text=meta(html,'og:description');imageUrl=meta(html,'og:image');if(title||text||imageUrl)importStatus='metadata_loaded';}}catch{/* Meta can require an access token; retain a safe editable draft. */}return reply({entry:{id:crypto.randomUUID(),sourceUrl,type:sourceUrl.includes('/reel/')?'reel':'post',title,text,imageUrl,publishedAt:'',status:'draft',enabled:true,importStatus}});}
export async function PUT(request:Request){const {user,error}=await authorized();if(error||!user)return error!;const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)return reply({error:'Origin mismatch'},403);const body=await request.json().catch(()=>({})),entries=normalize(body.entries);if(!entries.length&&Array.isArray(body.entries)&&body.entries.length)return reply({error:'Бүртгэлийн холбоосуудыг шалгана уу.'},400);const now=new Date().toISOString();await env.DB.prepare('INSERT INTO site_content (key,value_json,updated_by,updated_at) VALUES (?,?,?,?) ON CONFLICT(key) DO UPDATE SET value_json=excluded.value_json,updated_by=excluded.updated_by,updated_at=excluded.updated_at').bind(KEY,JSON.stringify(entries),user.id,now).run();return reply({entries,saved:true});}
