"use client";

import Link from "next/link";
import { useSiteLanguage } from "../lib/use-site-language";

export default function TermsPage() {
  const { t } = useSiteLanguage();
  return <main className="policy-page"><article><Link href="/register">← {t("Бүртгэл рүү буцах", "Back to registration")}</Link><span>iBeX WEBSITE ACCOUNT • 2026-09-v1</span><h1>{t("Үйлчилгээний нөхцөл", "Terms of service")}</h1><p>{t("Энэ нөхцөл нь iBeX-ийн олон нийтэд зориулсан веб сайтад хэрэглэгчийн бүртгэл үүсгэх, баталгаажуулах болон удирдах ажиллагаанд хамаарна.", "These terms govern the creation, verification and management of user accounts on the public iBeX website.")}</p><h2>{t("Бүртгэлийн зориулалт", "Purpose of registration")}</h2><p>{t("Веб хэрэглэгчийн бүртгэл нь мэдээлэл, үйлчилгээний хүсэлт болон цаашдын хэрэглэгчийн үйлчилгээнд ашиглагдана. Энэ бүртгэл нь үндсэн iBeX EAM/CMMS системийн tenant эрхийг автоматаар үүсгэхгүй.", "The website account supports information, service requests and future customer services. It does not automatically create tenant access to the core iBeX EAM/CMMS system.")}</p><h2>{t("Хэрэглэгчийн үүрэг", "User responsibilities")}</h2><p>{t("Хэрэглэгч үнэн зөв мэдээлэл оруулах, нууц үгээ хамгаалах, зөвшөөрөлгүй ашиглалт илэрвэл support@ibex.mn хаягаар мэдэгдэх үүрэгтэй.", "Users must provide accurate information, protect their password and report unauthorized use to support@ibex.mn.")}</p><h2>{t("Төлөв ба хамгаалалт", "Status and protection")}</h2><p>{t("И-мэйл баталгаажаагүй бүртгэл pending төлөвтэй байна. Аюулгүй байдлын эрсдэл, дүрэм зөрчсөн хэрэглээ эсвэл хэрэглэгчийн хүсэлтээр бүртгэлийг түр түгжих, түдгэлзүүлэх боломжтой.", "An unverified account remains pending. An account may be locked or suspended because of a security risk, policy violation or user request.")}</p><h2>{t("Устгах хүсэлт", "Deletion requests")}</h2><p>{t("Хэрэглэгч бүртгэлээсээ устгах хүсэлт гаргаж болно. Хүсэлт 30 хоногийн хүлээлгийн хугацаатай бөгөөд хууль, аюулгүй байдал, аудитын үндэслэлээр хадгалах шаардлагатай бүртгэл үүнд хамаарахгүй байж болно.", "Users may request account deletion. A 30-day waiting period applies, except where records must be retained for legal, security or audit purposes.")}</p><p className="policy-note">{t("Нийтэд нээхийн өмнө энэхүү баримт бичгийг эрх зүйн хяналтаар баталгаажуулна.", "This document must complete legal review before public launch.")}</p></article></main>;
}
