'use client';
import {FormEvent,useEffect,useState} from 'react';
type Entry={id:string;sourceUrl:string;type:string;title:string;text:string;imageUrl:string;publishedAt:string;status:string;enabled:boolean;importStatus?:string};
export default function SocialContentPage(){const[entries,setEntries]=useState<Entry[]>([]),[url,setUrl]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  useEffect(()=>{fetch('/api/admin/social-content',{cache:'no-store'}).then(async r=>{if(r.status===401){location.replace('/admin/login');return}if(r.status===403){location.replace('/admin');return}const p=await r.json();setEntries(p.entries||[])}).catch(()=>setError('Контентын мэдээллийг уншиж чадсангүй.'));},[]);
  function update(id:string,key:keyof Entry,value:any){setEntries(rows=>rows.map(row=>row.id===id?{...row,[key]:value}:row));}
  async function importLink(e:FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');const r=await fetch('/api/admin/social-content',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});const p=await r.json().catch(()=>({}));if(!r.ok)setError(p.error||'Холбоосыг оруулж чадсангүй.');else{setEntries(rows=>[p.entry,...rows]);setUrl('');setMessage(p.entry.importStatus==='metadata_loaded'?'Мэдээллийг татлаа. Хянаад нийтэлнэ үү.':'Холбоосыг ноорог болголоо. Meta зөвшөөрөлгүй тул мэдээллийг хянаж нөхнө үү.');}setBusy(false);}
  async function save(){setBusy(true);setError('');const r=await fetch('/api/admin/social-content',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({entries})});const p=await r.json().catch(()=>({}));if(!r.ok)setError(p.error||'Хадгалж чадсангүй.');else{setEntries(p.entries);setMessage('Мэдээ ба контентын өөрчлөлтийг хадгаллаа.');}setBusy(false);}
  return <main className="knowledge-page"><header className="knowledge-header"><a href="/admin" className="admin-users-back">← Сайтын админ</a><div><span className="admin-auth-kicker">iBeX PROJECT MONGOLIA</span><h1>Мэдээ ба контент</h1><p>Facebook пост, Reel-ийн холбоосоор ноорог үүсгэж, хянасны дараа нийтэлнэ.</p></div></header>{error?<div className="knowledge-alert error">{error}</div>:null}{message?<div className="knowledge-alert success">{message}</div>:null}<form className="admin-invite-card" onSubmit={importLink}><div><span className="admin-step">01</span><h2>Facebook холбоос оруулах</h2><p>Meta-аас нээлттэй metadata ирвэл автоматаар бөглөнө. Ирэхгүй бол холбоосыг хадгалж гараар хянана.</p></div><div><input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://www.facebook.com/..." required/><button className="admin-invite-submit" disabled={busy}>Холбоосоос ноорог үүсгэх</button></div></form><section className="admin-users-list"><div className="admin-users-list-head"><div><span className="admin-step">02</span><h2>Контентын жагсаалт</h2></div><button onClick={save} disabled={busy}>Бүгдийг хадгалах</button></div>{entries.map(row=><article className="admin-invite-card" key={row.id}><div>{row.imageUrl?<img src={row.imageUrl} alt="" style={{width:180,maxHeight:120,objectFit:'cover',borderRadius:12}}/>:null}<a href={row.sourceUrl} target="_blank" rel="noreferrer">Эх холбоос ↗</a></div><div className="knowledge-grid"><label>Төрөл<select value={row.type} onChange={e=>update(row.id,'type',e.target.value)}><option value="post">Post</option><option value="reel">Reel</option><option value="update">Системийн шинэчлэл</option><option value="event">Олон нийтийн арга хэмжээ</option><option value="research">Судалгаа, хөгжүүлэлт</option></select></label><label>Төлөв<select value={row.status} onChange={e=>update(row.id,'status',e.target.value)}><option value="draft">Draft</option><option value="published">Published</option><option value="archived">Archived</option></select></label><label className="wide">Гарчиг<input value={row.title} onChange={e=>update(row.id,'title',e.target.value)}/></label><label className="wide">Агуулга<textarea value={row.text} onChange={e=>update(row.id,'text',e.target.value)}/></label><label className="wide">Зургийн холбоос<input value={row.imageUrl} onChange={e=>update(row.id,'imageUrl',e.target.value)}/></label><label className="knowledge-switch"><input type="checkbox" checked={row.enabled} onChange={e=>update(row.id,'enabled',e.target.checked)}/> Идэвхтэй</label><button type="button" className="danger" onClick={()=>setEntries(rows=>rows.filter(x=>x.id!==row.id))}>Устгах</button></div></article>)}</section></main>}
